### ISSUE TITLE
Reading the Document field (LOB type) from the Employee File (9) in the demodb database results in error ADAGE35000: Record buffer too short.

### ISSUE THREAD

**Issue by mckeederek** [SoftwareAG/adabas-go-api#1]
I'm experimenting with the store/softwareag/adabas-ce:6.7.0 docker image. Reading the Document field (LOB type) from the Employee File (9) in the demodb database results in error ADAGE35000: Record buffer too short.
Would you be able to supply me with a code example that demonstrates retrieving document LOBs from the Employee file in the demodb database.

**Comment by thknieling** [comment]
The LOB record can get very huge. The adabas-go-api tries to increase the buffer accordingly but sometimes the maximum size is smaller then the needed buffers size.
You can increase the buffers using ReadRequest.RecordBufferShift:

```
request, _ := connection.CreateFileReadRequest(9)
request.RecordBufferShift = 64000
```

The buffer for LOB may be increase far more then 64000.
It is a good option to read LOB fields in a separate call using a separate ReadRequest instance created with `CreateFileReadRequest()` or `CreateMapReadRequest()`.

**Comment by mckeederek** [comment]
Thank you for the rapid response.  I tried setting request.RecordBufferShift  to both 64000 and 1000000 with the end result still being the  'ADAGE35000: Record buffer too short' error being received back from the Adabas database server. I'm trying to retrieve the documents for employee with personnelId=11300323 in the demodb employee file (9).     Could this issue be related to the default Adabas database configuration in the store/softwareag/adabas-ce:6.7.0 docker image?

**Comment by thknieling** [comment]
Please try it once more. The last release v1.3.9 fixes the issue reading the S0 group which contains a
multiplefield-enable large object field in a period group.

**Comment by mckeederek** [comment]
Your fix has certainly  resolved the 'Record buffer too short' error. Do you have sample code that demonstrates how to read the  LOB field SC (document) from the employee file and cast it correctly to a byte[] type?

**Comment by thknieling** [comment]
Just added a test case `TestConnectionRead9FieldDocument` using it.
`SC`(document) is an Multiple Field in an Period group. So you can reference it using two indexes.
You can evaluate the quantity of each field using the `Request.ValueQuantity()` method.
If you have the quantity, you can read the value of a entry in the group using for example

```
v, _ := record.SearchValue("SC[1,2]") // Get value for first period entry and second MU entry
raw := v.Bytes() // Get byte slice containing the raw data
````

If you need to read each entry in the query result, you can traverse through the tree using the `adatypes.TraverserValuesMethods` infrastructure. Here you define a callback which is called for each field in the field tree (even groups, period groups etc.)

**Comment by mckeederek** [comment]
I followed the pattern in your test method TestConnectionRead9FieldDocument. With query  predicate AA=11300323  ValueQuantity for "SC" is 1  and the ValueQuantity for "SC[1]" is 0.  I'm not getting the expected ValueQuantity value 3.
If I change the query predicate to be AA<=11300323 (multiple records being returned) the result record (AA=11300323) has a ValueQuantity  of 3 for "SC[1]".     The LOB field  behaviour is a little strange. Any thoughts on why the first query results in a ValueQuantity  of 0 for "SC[1]" ?

**Comment by thknieling** [comment]
Sorry can't reproduce it. Both queries with AA=11300323 and  AA<=11300323 work as expected.
Perhaps it depends on which platform you are working.
On Linux you can enable logging by setting the environment variable to ENABLE_DEBUG and run the test cases manually with

```
sh scripts/startTestAdabas.sh TestConnectionRead9FieldDocument
```

If it fails, can you have a look into the trace or send me the file. It located in the `logs` directory.
The database location may be adapted in the tests to the database id of your installation.

**Comment by mckeederek** [comment]
executing the TestConnectionRead9FieldDocument() test also results in  a ValueQuantity of 0 for "SC[1]".  I've attached both the source code and the output log.


[client_test.log](https://github.com/SoftwareAG/adabas-go-api/files/4092353/client_test.log)

[client_test.go.txt](https://github.com/SoftwareAG/adabas-go-api/files/4092361/client_test.go.txt)

**Comment by mckeederek** [comment]
Is there a more recent version of Adabas available as a docker image ?

**Comment by thknieling** [comment]
The new Adabas Docker image is on its way...

**Comment by thknieling** [comment]
Checked it using the Adabas v6.7 community edition. There seems to be an problem in that version.
With new Adabas v6.7.1 it works as expected. It's an problem in the version v6.7.

**Comment by mckeederek** [comment]
Thanks for investigating the issue.  Do you have any release dates for the next Adabas Docker image release?

**Comment by thknieling** [comment]
The image and everything is ready. It's only formalities do be done.

**Comment by thknieling** [comment]
Close after 20 days

**Comment by thknieling** [comment]
Adabas v6.7.1 Docker community edition is out now.
